---
abstract: 'Getopt::Long::DescriptivePod - write usage to Pod'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Getopt::Long::Descriptive: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Long-DescriptivePod
provides:
  Getopt::Long::DescriptivePod:
    file: lib/Getopt/Long/DescriptivePod.pm
    version: 0.01
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  English: 0
  Params::Validate: 0
  Perl6::Export::Attrs: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
